// packages/web/buildingai-ui/app/pages/console/system-setting/website/components/copyright.vue
<script lang="ts" setup>
import type { WebsiteCopyright } from "@buildingai/service/common";
import type { UpdateWebsiteRequest, WebsiteConfig } from "@buildingai/service/consoleapi/website";
import {
    apiGetWebsiteConfig,
    apiUpdateWebsiteConfig,
} from "@buildingai/service/consoleapi/website";
import { onMounted } from "vue";
import { useI18n } from "vue-i18n";

const { t } = useI18n();
const message = useMessage();

const state = shallowReactive<WebsiteCopyright>({
    displayName: "",
    iconUrl: "",
    url: "",
    copyrightText: "",
    copyrightBrand: "",
    copyrightUrl: "",
});

const websiteConfig = shallowRef<WebsiteConfig | null>(null);

const { lockFn: getWebsiteConfig, isLock: isLoadingConfig } = useLockFn(async () => {
    try {
        const config = await apiGetWebsiteConfig();
        websiteConfig.value = config;

        useFormData(state, config.copyright);
    } catch (error) {
        console.error("Get website config failed:", error);
    }
});

const { lockFn: onSubmit, isLock } = useLockFn(async () => {
    try {
        // 构建更新数据，只传递版权部分
        const updateData: UpdateWebsiteRequest = {
            copyright: {
                displayName: state.displayName,
                iconUrl: state.iconUrl,
                url: state.url,
                copyrightText: state.copyrightText,
                copyrightBrand: state.copyrightBrand,
                copyrightUrl: state.copyrightUrl,
            },
        };

        await apiUpdateWebsiteConfig(updateData);
        message.success(t("system.website.messages.saveSuccess"));

        // 重新获取配置以确保数据同步
        await getWebsiteConfig();
    } catch (error) {
        console.error("Save failed:", error);
    }
});

const resetForm = () => {
    if (websiteConfig.value) {
        state.displayName = websiteConfig.value.copyright.displayName || "";
        state.iconUrl = websiteConfig.value.copyright.iconUrl || "";
        state.url = websiteConfig.value.copyright.url || "";
        state.copyrightText = websiteConfig.value.copyright.copyrightText || "";
        state.copyrightBrand = websiteConfig.value.copyright.copyrightBrand || "";
        state.copyrightUrl = websiteConfig.value.copyright.copyrightUrl || "";
        message.info(t("system.website.messages.resetSuccess"));
    } else {
        state.displayName = "";
        state.iconUrl = "";
        state.url = "";
        state.copyrightText = "";
        state.copyrightBrand = "";
        state.copyrightUrl = "";
        message.info(t("system.website.messages.resetEmpty"));
    }
};

onMounted(() => getWebsiteConfig());
</script>

<template>
    <div class="copyright-container mt-8">
        <!-- 表单 -->
        <UForm :state="state" class="space-y-6" @submit="onSubmit">
            <h4 class="mb-2 text-lg font-bold">
                {{ t("system.website.copyright.sections.filing") }}
            </h4>
            <UFormField name="displayName" :label="t('system.website.copyright.displayName.label')">
                <UInput
                    v-model="state.displayName"
                    size="lg"
                    :ui="{ root: 'w-full' }"
                    :placeholder="t('system.website.copyright.displayName.placeholder')"
                />
            </UFormField>

            <UFormField name="iconUrl" :label="t('system.website.copyright.icon.label')">
                <div class="flex items-start gap-4">
                    <BdUploader
                        v-model="state.iconUrl"
                        class="h-24 w-24"
                        :text="t('system.website.copyright.icon.upload')"
                        icon="i-lucide-upload"
                        accept=".jpg,.png,.jpeg"
                        :maxCount="1"
                        :single="true"
                    />
                </div>
            </UFormField>

            <UFormField name="url" :label="t('system.website.copyright.url.label')">
                <UInput
                    v-model="state.url"
                    size="lg"
                    :ui="{ root: 'w-full' }"
                    :placeholder="t('system.website.copyright.url.placeholder')"
                />
            </UFormField>

            <h4 class="mb-2 text-lg font-bold">
                {{ t("system.website.copyright.sections.copyright") }}
            </h4>

            <UFormField
                name="copyrightText"
                :label="t('system.website.copyright.copyrightInfo.label')"
            >
                <div class="flex w-full gap-4">
                    <UInput
                        v-model="state.copyrightText"
                        size="lg"
                        class="flex-1"
                        :placeholder="t('system.website.copyright.copyrightInfo.textPlaceholder')"
                    />
                    <UInput
                        v-model="state.copyrightBrand"
                        size="lg"
                        class="flex-1"
                        :placeholder="t('system.website.copyright.copyrightInfo.brandPlaceholder')"
                    />
                </div>
            </UFormField>

            <UFormField
                name="copyrightUrl"
                :label="t('system.website.copyright.copyrightUrl.label')"
            >
                <UInput
                    v-model="state.copyrightUrl"
                    size="lg"
                    :ui="{ root: 'w-full' }"
                    :placeholder="t('system.website.copyright.copyrightUrl.placeholder')"
                />
            </UFormField>

            <div class="bg-background sticky bottom-0 flex space-x-3 py-4">
                <AccessControl :codes="['system-website:setConfig']">
                    <UButton
                        type="submit"
                        color="primary"
                        :loading="isLock"
                        :disabled="isLock || isLoadingConfig"
                    >
                        {{
                            isLock
                                ? t("system.website.actions.saving")
                                : t("system.website.actions.saveChanges")
                        }}
                    </UButton>
                </AccessControl>
                <UButton
                    type="reset"
                    color="neutral"
                    variant="outline"
                    :disabled="isLock || isLoadingConfig"
                    @click="resetForm"
                >
                    {{ t("system.website.actions.reset") }}
                </UButton>
            </div>
        </UForm>
    </div>
</template>

// packages/client/src/pages/console/system/website-config/_components/copyright.tsx
import { useI18n } from "@buildingai/i18n";
import {
  useSetWebsiteConfigMutation,
  useWebsiteConfigQuery,
  type WebsiteConfigResponse,
  type WebsiteCopyright as ApiCopyright,
} from "@buildingai/services/console";
import { PermissionGuard } from "@buildingai/ui/components/auth/permission-guard";
import { Button } from "@buildingai/ui/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
} from "@buildingai/ui/components/ui/form";
import { ImageUpload } from "@buildingai/ui/components/ui/image-upload";
import { Input } from "@buildingai/ui/components/ui/input";
import { Loader2 } from "lucide-react";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";

export type CopyrightFormValues = {
  displayName: string;
  iconUrl: string;
  url: string;
  copyrightText: string;
  copyrightBrand: string;
  copyrightUrl: string;
};

const defaultValues: CopyrightFormValues = {
  displayName: "",
  iconUrl: "",
  url: "",
  copyrightText: "",
  copyrightBrand: "",
  copyrightUrl: "",
};

export default function Copyright() {
  const { t } = useI18n();
  const { data: rawData, isLoading } = useWebsiteConfigQuery();
  const data = rawData as WebsiteConfigResponse | undefined;
  const setMutation = useSetWebsiteConfigMutation({
    onSuccess: () => toast.success(t("system.websiteConfig.copyright.saveSuccess")),
    onError: (e) => {
      console.log(`${t("system.websiteConfig.copyright.saveFailed", { message: e.message })}`);
    },
  });

  const form = useForm<CopyrightFormValues>({ defaultValues });

  useEffect(() => {
    if (!data?.copyright) return;
    const c = data.copyright;
    form.reset({
      displayName: c.displayName ?? "",
      iconUrl: c.iconUrl ?? "",
      url: c.url ?? "",
      copyrightText: c.copyrightText ?? "",
      copyrightBrand: c.copyrightBrand ?? "",
      copyrightUrl: c.copyrightUrl ?? "",
    });
  }, [data?.copyright, form]);

  const onSubmit = (values: CopyrightFormValues) => {
    setMutation.mutate({
      copyright: values as ApiCopyright,
    });
  };
  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="text-muted-foreground size-8 animate-spin" />
      </div>
    );
  }

  const loadedCopyright = data?.copyright;

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        <h4 className="text-lg font-bold">{t("system.websiteConfig.copyright.filingInfo")}</h4>
        <FormField
          control={form.control}
          name="displayName"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{t("system.websiteConfig.copyright.displayName.label")}</FormLabel>
              <FormControl>
                <Input
                  placeholder={t("system.websiteConfig.copyright.displayName.placeholder")}
                  {...field}
                />
              </FormControl>
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="iconUrl"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{t("system.websiteConfig.copyright.iconUrl.label")}</FormLabel>
              <FormControl>
                <ImageUpload
                  size="lg"
                  value={field.value}
                  onChange={(url) => field.onChange(url ?? "")}
                />
              </FormControl>
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="url"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{t("system.websiteConfig.copyright.url.label")}</FormLabel>
              <FormControl>
                <Input
                  placeholder={t("system.websiteConfig.copyright.url.placeholder")}
                  {...field}
                />
              </FormControl>
            </FormItem>
          )}
        />
        <h4 className="text-lg font-bold">{t("system.websiteConfig.copyright.copyrightInfo")}</h4>
        <div className="flex w-full flex-col gap-2">
          <FormLabel>{t("system.websiteConfig.copyright.copyrightInfo")}</FormLabel>
          <div className="flex w-full gap-4">
            <FormField
              control={form.control}
              name="copyrightText"
              render={({ field }) => (
                <FormItem className="flex-1">
                  <FormControl>
                    <Input
                      {...field}
                      placeholder={t("system.websiteConfig.copyright.copyrightText.placeholder")}
                    />
                  </FormControl>
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="copyrightBrand"
              render={({ field }) => (
                <FormItem className="flex-1">
                  <FormControl>
                    <Input
                      {...field}
                      placeholder={t("system.websiteConfig.copyright.copyrightBrand.placeholder")}
                    />
                  </FormControl>
                </FormItem>
              )}
            />
          </div>
        </div>
        <FormField
          control={form.control}
          name="copyrightUrl"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{t("system.websiteConfig.copyright.copyrightUrl.label")}</FormLabel>
              <FormControl>
                <Input
                  placeholder={t("system.websiteConfig.copyright.copyrightUrl.placeholder")}
                  {...field}
                />
              </FormControl>
            </FormItem>
          )}
        />
        <div className="flex gap-2">
          <PermissionGuard permissions="system-website:setConfig">
            <Button type="submit" disabled={setMutation.isPending}>
              {setMutation.isPending && <Loader2 className="mr-2 size-4 animate-spin" />}
              {t("system.websiteConfig.copyright.save")}
            </Button>

            <Button
              type="button"
              variant="outline"
              onClick={() =>
                loadedCopyright &&
                form.reset({
                  displayName: loadedCopyright.displayName ?? "",
                  iconUrl: loadedCopyright.iconUrl ?? "",
                  url: loadedCopyright.url ?? "",
                  copyrightText: loadedCopyright.copyrightText ?? "",
                  copyrightBrand: loadedCopyright.copyrightBrand ?? "",
                  copyrightUrl: loadedCopyright.copyrightUrl ?? "",
                })
              }
            >
              {t("system.websiteConfig.copyright.reset")}
            </Button>
          </PermissionGuard>
        </div>
      </form>
    </Form>
  );
}
